// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PurchasingRequestFormController from "./purchasing_request_form_controller"
application.register("purchasing-request-form", PurchasingRequestFormController)

import WineRatioController from "./wine_ratio_controller"
application.register("wine-ratio", WineRatioController)
