// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RowClickController from "./row_click_controller"
application.register("row-click", RowClickController)

import WineClickController from "./wine_click_controller"
application.register("wine-click", WineClickController)

import WineRatioController from "./wine_ratio_controller"
application.register("wine-ratio", WineRatioController)
