meta_product_name: "Stor-eYe"
meta_title: "Stor-eYe - Keep an eye on your storages"
meta_description: "Stor-eYe is an App that help restaurants owner to manage their wine stocks."
meta_image: "stor-eye_cover.png"
